---
- name: Remove host from load balancer service group
  netscaler.adc.servicegroup_servicegroupmember_binding:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    servicegroupname: dr-group
    servername: "{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost
