---
- name: Add hosts to Citrix Load Balancer
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false
  serial: 1

  roles:
    - citrix_add

- name: Set E-mail
  hosts: localhost
  gather_facts: false

  roles:
    - citrix_email
