---
- name: Setup server
  citrix.adc.citrix_adc_server:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    state: present
    name: "{{ inventory_hostname }}"
    ipaddress: "{{ ip_addr }}"
    validate_certs: false
  delegate_to: localhost

- name: Setup service group and add host
  citrix.adc.citrix_adc_servicegroup:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    servicegroupname: service-group-https
    maxclient: "4000"
    servicetype: TCP
    validate_certs: false
    servicemembers:
      mode: bind
      attributes:
        - servername: "{{ inventory_hostname }}"
          port: 443
          weight: "50"
    monitor_bindings:
      mode: exact
      attributes:
        - monitor_name: https
          weight: "50"
  delegate_to: localhost
