---
- name: Set stats for the e-mail body and ServiceNow
  ansible.builtin.set_stats:
    data:
      email_body: "{{ email_body }} Load Balancer: https://citrixlb.shadowman.dev "
      work_notes: "{{ work_notes }} [code]<a href='https://citrixlb.shadowman.dev'>Load Balancer</a>[/code] "
  when: email_body is defined
