---
- name: IDM_update
  community.general.ipa_host:
    name: citrixlb.shadowman.dev
    ip_address: 172.16.0.123
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: present
    force: true
  delegate_to: localhost
  become: false
