---
- name: Disable Server from LB
  netscaler.adc.server:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    state: disabled
    ipaddress: "{{ ip_addr }}"
    name: "{{ inventory_hostname }}"
    validate_certs: false
  delegate_to: localhost
