---
- name: Delete Virtual Server
  netscaler.adc.lbvserver:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    name: lb-vserver-https
    state: absent
    validate_certs: false
  notify: IDM_update

- name: Delete Servicegroup
  netscaler.adc.servicegroup:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    servicegroupname: service-group-https
    state: absent
    validate_certs: false
